# Generated by Django 5.1.1 on 2024-09-14 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('licencia', models.CharField(max_length=255)),
                ('fechaini', models.DateField()),
                ('fechafin', models.DateField()),
                ('logo', models.ImageField(blank=True, max_length=200, null=True, upload_to='empresas/')),
                ('about', models.CharField(blank=True, max_length=100, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('usercreate', models.CharField(max_length=20)),
                ('usermodify', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('ipsucursal', models.CharField(max_length=15)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('usercreate', models.CharField(max_length=20)),
                ('usermodify', models.CharField(blank=True, max_length=20, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configuracion.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='CorrelativoFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativoini', models.CharField(max_length=100)),
                ('correlativofin', models.CharField(max_length=100)),
                ('tipodocumento', models.CharField(blank=True, choices=[('TICKET', 'TICKET'), ('FACTURA', 'FACTURA'), ('CREDITO FISCAL', 'CREDITO FISCAL')], max_length=15, null=True)),
                ('numdocumentoasig', models.CharField(max_length=50)),
                ('fechadocumento', models.DateField()),
                ('correlativoact', models.CharField(max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('usercreate', models.CharField(max_length=20)),
                ('usermodify', models.CharField(blank=True, max_length=20, null=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configuracion.sucursale')),
            ],
        ),
        migrations.CreateModel(
            name='Configuracione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilidadactive', models.BooleanField()),
                ('utilidad', models.IntegerField(blank=True, null=True)),
                ('ivaactive', models.BooleanField()),
                ('iva', models.IntegerField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('usercreate', models.CharField(max_length=20)),
                ('usermodify', models.CharField(blank=True, max_length=20, null=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configuracion.sucursale')),
            ],
        ),
    ]
